### ISSUE TITLE
[ FIX ] 마무리해야할 작업 리스트

### ISSUE THREAD

**Issue by munawiki** [codestates/WhyNotWorking-client#114]
### ISSUE
- Group:  `client`
- Type: `fix`

### TODO
1. [x] edit profile 아직 완전하게 새로고침 안 됨 (nav 부분)
2. [x] 깃헙 로그인
3. [x] 회원가입 디테일 수정
4. [x] 로그인 회원가입 validation 추가
5. [ ] 홈, 푸터 구현
6. [x] tags 아직 완전 구현 X
7. [x] users, tags 검색도 미구현
8. [ ] 열심히 버그 찾기
9. [x] amplify dev 브런치 말고 main 브런치로 변경할 것 (최고 우선순위) *완료
10. [x] 페이지네이션

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
